### ISSUE TITLE
Hacktoberfest 2020: Make it easier to install

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/gocat#4]
# Hacktoberfest:  Add install target in Makefile
Currently, there's no way to install `gocat` globally into the system. As such, we need to provide users ability to easily install our program. For example:
```
# This should copy the binary one of the PATH
$ make install
# So user can run the binary as such from anywhere
$ gocat --version
```

#### References: 
- https://github.com/tuladhar/set-brightness/blob/main/Makefile

Puru,
Happy Hacking

**Comment by pavan-kalyan** [comment]
Wouldn't the exact same makefile work (with the program name changed)?

**Comment by tuladhar** [comment]
Yes, it should @pavan-kalyan. Go ahead and submit the pull request.

**Comment by pavan-kalyan** [comment]
Thanks for the clarification @tuladhar.
I think I should leave this for someone making their first PR.
Thanks for participating as a maintainer in hacktoberfest!!

**Comment by vimarsh6739** [comment]
The way I see it, you just need to copy the binary to /usr/local/bin after building it. Or is there something I'm misunderstanding here @tuladhar ?  
Can I take this up?

**Comment by tuladhar** [comment]
That's right @vimarsh6739. You need to copy it to the system path directory in this case `/usr/local/bin` and make it executable. 

Sure you can take it. I've assigned it to you.
